on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1
      - name: Build Exe
        working-directory: ./Traincrew_Decrease_graph
        run: |
          msbuild `
            -p:OutputPath=../out `
            -p:PublishSingleFile=true `
            -p:Configuration=Release `
            -p:DebugSymbols=false `
            -p:DebugType=None
      - name: Upload Exe
        uses: actions/upload-artifact@v3
        with:
          name: Traincrew_Decrease_graph
          path: out